[package]
name = "gnvim"
version = "0.1.0"
authors = ["Ville Hakulinen <ville.hakulinen@gmail.com>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
rmpv = { version = "1.0.0", features = ["with-serde"] }
once_cell = "1.10.0"
clap = { version = "3.1.18", features = ["derive", "env"] }

[dependencies.gtk]
package = "gtk4"
version = "0.4"
features = ["v4_4"]

[dependencies.glib]
version = "0.15"
features = ["log_macros"]

[dependencies.nvim]
package = "nvim-rs"
path = "../lib/nvim-rs"

[dependencies.gio-compat]
path = "../lib/gio-compat"

[build-dependencies.gtk]
package = "gtk4"
version = "0.4.7"
features = ["v4_4"]
